#!/bin/bash
# One-shot bootstrap for the VERITEK IoT host on Google Cloud.
#
# Idempotent: safe to re-run after a config change or a failed attempt.
#
#   sudo ./deploy/scripts/gcp-bootstrap.sh
#
# What it does, in order:
#   1. reads deployment secrets from Google Secret Manager (never from git)
#   2. writes deploy/env/<environment>.env, mode 600
#   3. initialises Mosquitto's credential store on first run
#   4. obtains the TLS certificate (standalone, port 80 must be free)
#   5. installs systemd timers for certificate renewal and database backups
#   6. builds and starts the stack
#
# Environment overrides:
#   PROJECT_ID    GCP project            (default: veritek)
#   ENVIRONMENT   staging | production   (default: staging)
#   PUBLIC_IP     host public IP         (default: detected from metadata)
#   BASE_DOMAIN   DNS suffix             (default: <dashed-ip>.sslip.io)
#   ACME_EMAIL    Let's Encrypt contact  (optional; unset registers without one)

set -euo pipefail

PROJECT_ID="${PROJECT_ID:-veritek}"
ENVIRONMENT="${ENVIRONMENT:-staging}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="$REPO_DIR/deploy"
ENV_FILE="$DEPLOY_DIR/env/$ENVIRONMENT.env"
LE_DIR="$DEPLOY_DIR/letsencrypt"
CERT_DIR="$DEPLOY_DIR/certs"
WEBROOT="$DEPLOY_DIR/certbot-webroot"
COMPOSE="docker compose -f $DEPLOY_DIR/docker-compose.prod.yml --env-file $ENV_FILE"

log() { echo "[bootstrap] $*"; }

# --------------------------------------------------------------- 0. identity --

PUBLIC_IP="${PUBLIC_IP:-$(curl -sf -H 'Metadata-Flavor: Google' \
  'http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip' || true)}"
[ -n "$PUBLIC_IP" ] || { echo "could not determine the public IP; pass PUBLIC_IP=" >&2; exit 1; }

# sslip.io resolves any name containing the dashed IP, which gives us real DNS
# names and a publicly trusted certificate without owning a domain yet. Swap
# BASE_DOMAIN for the real domain when there is one; only DNS and this variable
# change, never the gateways' firmware.
BASE_DOMAIN="${BASE_DOMAIN:-$(echo "$PUBLIC_IP" | tr '.' '-').sslip.io}"
# Extra browser origins allowed to call the API. The dashboard is also hosted
# on Vercel, which is a different origin; CORS must name it, because a
# wildcard is not usable once requests carry an Authorization header.
EXTRA_CORS_ORIGINS="${EXTRA_CORS_ORIGINS:-https://veritekiot.vercel.app}"
MQTT_HOST_NAME="mqtt.$BASE_DOMAIN"
API_HOST_NAME="api.$BASE_DOMAIN"

log "project=$PROJECT_ID environment=$ENVIRONMENT ip=$PUBLIC_IP"
log "mqtt=$MQTT_HOST_NAME api=$API_HOST_NAME"

# ------------------------------------------------- 1-2. secrets and env file --

secret() {
  # Under `set -e` a failed read ends the script inside a command substitution,
  # with no output at all - so say which secret, and the usual reason.
  local value
  if ! value="$(gcloud secrets versions access latest --secret="veritek-$1" --project="$PROJECT_ID" 2>/dev/null)"; then
    echo "[bootstrap] cannot read secret veritek-$1: it is missing, or this VM's service account" \
         "has no roles/secretmanager.secretAccessor on it (access is granted per secret)" >&2
    return 1
  fi
  printf '%s' "$value"
}

log "reading secrets from Secret Manager"
POSTGRES_PASSWORD="$(secret postgres-password)"
BROKER_WEBHOOK_SECRET="$(secret broker-webhook-secret)"
MQTT_SERVICE_PASSWORD="$(secret mqtt-service-password)"
# Broker-admin identity the backend uses to create and revoke device logins.
MQTT_CONTROL_PASSWORD="$(secret mqtt-control-password)"
JWT_SECRET="$(secret jwt-secret)"
TOKEN_PEPPER="$(secret token-pepper)"
SEED_ADMIN_PASSWORD="$(secret seed-admin-password)"
GRAFANA_ADMIN_PASSWORD="$(secret grafana-admin-password)"
METRICS_TOKEN="$(secret metrics-token)"

for name in POSTGRES_PASSWORD BROKER_WEBHOOK_SECRET MQTT_SERVICE_PASSWORD MQTT_CONTROL_PASSWORD JWT_SECRET TOKEN_PEPPER SEED_ADMIN_PASSWORD; do
  [ -n "${!name}" ] || { echo "secret $name is empty - check Secret Manager access" >&2; exit 1; }
done

mkdir -p "$DEPLOY_DIR/env" "$LE_DIR" "$CERT_DIR" "$WEBROOT"
umask 077
cat > "$ENV_FILE" <<ENVEOF
# Generated by gcp-bootstrap.sh. Secrets come from Google Secret Manager;
# this file is mode 600 and is never committed. Re-run the script to refresh it.
DEPLOY_ENVIRONMENT=$ENVIRONMENT
LOG_LEVEL=info

MQTT_PUBLIC_HOST=$MQTT_HOST_NAME
API_PUBLIC_HOST=$API_HOST_NAME
CORS_ORIGINS=https://$API_HOST_NAME${EXTRA_CORS_ORIGINS:+,$EXTRA_CORS_ORIGINS}
GRAFANA_ROOT_URL=http://localhost:3000

POSTGRES_USER=veritek
POSTGRES_DB=veritek_iot
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

MOSQUITTO_VERSION=2.1.2-alpine
BROKER_WEBHOOK_SECRET=$BROKER_WEBHOOK_SECRET

MQTT_SERVICE_USERNAME=energy-backend-ingestion
MQTT_SERVICE_PASSWORD=$MQTT_SERVICE_PASSWORD
MQTT_CONTROL_USERNAME=veritek-control
MQTT_CONTROL_PASSWORD=$MQTT_CONTROL_PASSWORD
MQTT_TOPIC_ROOT=energy/v1
MQTT_VENDOR_TOPICS=
MQTT_SUBSCRIBE_TOPICS=

# Staging keeps plaintext 1883 reachable for commissioning, because the unit's
# TLS support is unverified. Production sets both back to false/127.0.0.1.
MQTT_PLAINTEXT_ENABLED=$([ "$ENVIRONMENT" = "staging" ] && echo true || echo false)
MQTT_PLAIN_BIND=$([ "$ENVIRONMENT" = "staging" ] && echo 0.0.0.0 || echo 127.0.0.1)

JWT_SECRET=$JWT_SECRET
TOKEN_PEPPER=$TOKEN_PEPPER
SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@veritek.com}
SEED_ADMIN_PASSWORD=$SEED_ADMIN_PASSWORD
METRICS_TOKEN=$METRICS_TOKEN

# Staging auto-registers an unknown gateway so its first packet is attributable.
AUTO_PROVISION_GATEWAYS=$([ "$ENVIRONMENT" = "staging" ] && echo true || echo false)
AUTO_PROVISION_METERS=$([ "$ENVIRONMENT" = "staging" ] && echo true || echo false)

GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
BACKUP_BUCKET=gs://veritek-iot-backups
BACKUP_RETENTION_DAYS=30
ENVEOF
umask 022
chmod 600 "$ENV_FILE"
log "wrote $ENV_FILE"

# ------------------------------------------- 3. broker credential store --

# Mosquitto's Dynamic Security plugin will not start without its store, and the
# store needs one admin identity - the backend's control account - before
# anything else can be created through it. Every other credential (the
# backend's ingestion login, each device) is created by the backend over the
# control API. Done once: an existing store holds every device's login and is
# never overwritten.
log "checking the Mosquitto credential store"
if $COMPOSE run --rm --no-deps -T --entrypoint sh mosquitto \
     -c 'test -s /mosquitto/data/dynamic-security.json' >/dev/null 2>&1; then
  log "credential store present; leaving it untouched"
else
  log "initialising the credential store with the control identity"
  # Passed through the environment rather than the command line, so the
  # password is not in the host's process list.
  $COMPOSE run --rm --no-deps -T \
    -e DYNSEC_USER=veritek-control -e DYNSEC_PASS="$MQTT_CONTROL_PASSWORD" \
    --entrypoint sh mosquitto -c '
      mosquitto_ctrl dynsec init /mosquitto/data/dynamic-security.json "$DYNSEC_USER" "$DYNSEC_PASS" >/dev/null &&
      chown -R mosquitto:mosquitto /mosquitto/data &&
      chmod 600 /mosquitto/data/dynamic-security.json'
  log "credential store initialised"
fi

# ------------------------------------------------------------ 4. certificate --

install_certs() {
  local live="$LE_DIR/live/$MQTT_HOST_NAME"
  [ -d "$live" ] || { echo "no certificate at $live" >&2; return 1; }
  cp -L "$live/fullchain.pem" "$CERT_DIR/fullchain.pem"
  cp -L "$live/privkey.pem"   "$CERT_DIR/privkey.pem"
  cp -L "$live/chain.pem"     "$CERT_DIR/chain.pem"
  chmod 644 "$CERT_DIR/fullchain.pem" "$CERT_DIR/chain.pem"
  # Readable by root (nginx's master process) and group 1883 - the mosquitto
  # user inside its container - and by nothing else.
  chown 0:1883 "$CERT_DIR/privkey.pem"
  chmod 640 "$CERT_DIR/privkey.pem"
}

if [ -f "$CERT_DIR/fullchain.pem" ] && openssl x509 -checkend 604800 -noout -in "$CERT_DIR/fullchain.pem" >/dev/null 2>&1; then
  log "certificate present and valid for more than 7 days; skipping issuance"
else
  log "requesting a certificate for $MQTT_HOST_NAME and $API_HOST_NAME"
  # Standalone needs port 80, so stop anything holding it first.
  $COMPOSE stop nginx >/dev/null 2>&1 || true

  email_args=(--register-unsafely-without-email)
  if [ -n "${ACME_EMAIL:-}" ]; then
    email_args=(--email "$ACME_EMAIL")
  fi

  docker run --rm -p 80:80 \
    -v "$LE_DIR:/etc/letsencrypt" \
    certbot/certbot certonly --standalone -n --agree-tos \
      "${email_args[@]}" \
      -d "$MQTT_HOST_NAME" -d "$API_HOST_NAME"

  install_certs
  log "certificate installed"
fi

# Applied every run, not only at issuance: a host migrating from the EMQX setup
# still has a key owned for EMQX's uid, which Mosquitto cannot read.
if [ -f "$CERT_DIR/privkey.pem" ]; then
  chown 0:1883 "$CERT_DIR/privkey.pem"
  chmod 640 "$CERT_DIR/privkey.pem"
fi

# --------------------------------------------- 5. renewal and backup timers --

log "installing systemd timers"

cat > /usr/local/bin/veritek-cert-renew.sh <<RENEWEOF
#!/bin/bash
# Renew the TLS certificate and reload the services that hold it.
#
# Runs on the host, not in a container: reloading nginx and Mosquitto needs the
# Docker socket, and handing that to a container is handing it root.
set -euo pipefail
REPO_DIR="$REPO_DIR"
DEPLOY_DIR="\$REPO_DIR/deploy"
docker run --rm \\
  -v "\$DEPLOY_DIR/letsencrypt:/etc/letsencrypt" \\
  -v "\$DEPLOY_DIR/certbot-webroot:/var/www/certbot" \\
  certbot/certbot renew --webroot -w /var/www/certbot --quiet

LIVE="\$DEPLOY_DIR/letsencrypt/live/$MQTT_HOST_NAME"
if [ -f "\$LIVE/fullchain.pem" ]; then
  if ! cmp -s "\$LIVE/fullchain.pem" "\$DEPLOY_DIR/certs/fullchain.pem"; then
    echo "[cert-renew] new certificate, installing and reloading"
    cp -L "\$LIVE/fullchain.pem" "\$DEPLOY_DIR/certs/fullchain.pem"
    cp -L "\$LIVE/privkey.pem"   "\$DEPLOY_DIR/certs/privkey.pem"
    cp -L "\$LIVE/chain.pem"     "\$DEPLOY_DIR/certs/chain.pem"
    chmod 644 "\$DEPLOY_DIR/certs/fullchain.pem" "\$DEPLOY_DIR/certs/chain.pem"
    chown 0:1883 "\$DEPLOY_DIR/certs/privkey.pem"
    chmod 640 "\$DEPLOY_DIR/certs/privkey.pem"
    docker exec veritek-nginx nginx -s reload || true
    # A few seconds' restart every ~60 days: devices reconnect with backoff,
    # and sessions and queued messages are saved on the way down.
    docker restart veritek-mosquitto || true
  fi
fi
RENEWEOF
chmod +x /usr/local/bin/veritek-cert-renew.sh

cat > /usr/local/bin/veritek-backup.sh <<BACKUPEOF
#!/bin/bash
# Nightly database backup to Cloud Storage (spec section 22).
set -euo pipefail
ENV_FILE="$ENV_FILE"
# shellcheck disable=SC1090
. "\$ENV_FILE"
BACKUP_DIR=/var/backups/veritek
STAMP="\$(date -u +%Y%m%dT%H%M%SZ)"
FILE="\$BACKUP_DIR/veritek-\${POSTGRES_DB}-\${STAMP}.sql.gz"
mkdir -p "\$BACKUP_DIR"

docker exec -e PGPASSWORD="\$POSTGRES_PASSWORD" veritek-timescaledb \\
  pg_dump -U "\$POSTGRES_USER" -d "\$POSTGRES_DB" --no-owner --no-privileges \\
  | gzip -9 > "\$FILE"

SIZE="\$(stat -c %s "\$FILE")"
if [ "\$SIZE" -lt 1024 ]; then
  echo "[backup] FAILED: dump is only \$SIZE bytes" >&2
  rm -f "\$FILE"
  exit 1
fi
echo "[backup] wrote \$FILE (\$SIZE bytes)"

# Off-instance copy. A backup on the same disk survives neither a disk failure
# nor a deleted VM.
if [ -n "\${BACKUP_BUCKET:-}" ]; then
  gcloud storage cp "\$FILE" "\$BACKUP_BUCKET/" --quiet && echo "[backup] uploaded to \$BACKUP_BUCKET"
fi

# The broker's credential store. Every device login lives in it; lose it and
# every device is locked out until each one is re-credentialed by hand. It
# holds salted hashes, never plaintext passwords.
DYNSEC="\$BACKUP_DIR/veritek-dynsec-\${STAMP}.json.gz"
if docker exec veritek-mosquitto cat /mosquitto/data/dynamic-security.json 2>/dev/null | gzip -9 > "\$DYNSEC" \\
   && [ "\$(stat -c %s "\$DYNSEC")" -gt 100 ]; then
  chmod 600 "\$DYNSEC"
  echo "[backup] wrote \$DYNSEC"
  if [ -n "\${BACKUP_BUCKET:-}" ]; then
    gcloud storage cp "\$DYNSEC" "\$BACKUP_BUCKET/" --quiet && echo "[backup] uploaded broker credentials"
  fi
else
  echo "[backup] FAILED: could not read the broker credential store" >&2
  rm -f "\$DYNSEC"
  DYNSEC_FAILED=1
fi

find "\$BACKUP_DIR" -name 'veritek-*.sql.gz' -mtime "+\${BACKUP_RETENTION_DAYS:-30}" -delete
find "\$BACKUP_DIR" -name 'veritek-dynsec-*.json.gz' -mtime "+\${BACKUP_RETENTION_DAYS:-30}" -delete
# Fail the unit after cleanup, so a broken credential backup shows up in
# systemctl rather than scrolling past in a log.
[ -z "\${DYNSEC_FAILED:-}" ]
BACKUPEOF
chmod +x /usr/local/bin/veritek-backup.sh

write_timer() {
  local name="$1" description="$2" schedule="$3" script="$4"
  cat > "/etc/systemd/system/$name.service" <<UNITEOF
[Unit]
Description=$description
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=$script
UNITEOF
  cat > "/etc/systemd/system/$name.timer" <<TIMEREOF
[Unit]
Description=$description (timer)

[Timer]
OnCalendar=$schedule
Persistent=true
RandomizedDelaySec=1800

[Install]
WantedBy=timers.target
TIMEREOF
  systemctl daemon-reload
  systemctl enable --now "$name.timer" >/dev/null 2>&1
}

write_timer veritek-cert-renew "VERITEK TLS certificate renewal" "*-*-* 03,15:17:00" /usr/local/bin/veritek-cert-renew.sh
write_timer veritek-backup "VERITEK database backup" "*-*-* 02:30:00" /usr/local/bin/veritek-backup.sh
log "timers installed: $(systemctl list-timers --no-pager 'veritek-*' 2>/dev/null | grep -c veritek || echo 0)"

# ---------------------------------------------------------- 6. dashboard --

# Built here rather than committed: a bundle in git goes stale the moment the
# source changes, and nginx serves it as plain static files.
log "building the dashboard"
FRONTEND_DIR="$(dirname "$REPO_DIR")"
if [ -f "$FRONTEND_DIR/package.json" ]; then
  if docker run --rm \
      -v "$FRONTEND_DIR:/app" -w /app \
      -e npm_config_cache=/tmp/.npm \
      node:22-alpine sh -c "npm ci --no-audit --no-fund && npm run build"
  then
    # Clear the directory's CONTENTS, never the directory itself. nginx bind
    # mounts this path, and a bind mount follows the inode - delete and recreate
    # the directory and the container stays attached to the old, unlinked one
    # and serves nothing.
    mkdir -p "$DEPLOY_DIR/dashboard"
    find "$DEPLOY_DIR/dashboard" -mindepth 1 -delete
    cp -r "$FRONTEND_DIR/dist/." "$DEPLOY_DIR/dashboard/"
    log "dashboard built"
  else
    log "WARNING: dashboard build failed; nginx will keep serving the previous build"
  fi
else
  log "no frontend package.json found; skipping the dashboard build"
fi

# -------------------------------------------------------------- 7. the stack --

log "building and starting the stack"
# --remove-orphans takes down any service this file no longer defines (the EMQX
# broker Mosquitto replaced). Named volumes are left in place.
$COMPOSE up -d --build --remove-orphans

log "waiting for the backend to become ready"
for _ in $(seq 1 60); do
  if curl -sf http://127.0.0.1:4000/api/health/ready >/dev/null 2>&1 \
     || docker exec veritek-backend node -e "fetch('http://127.0.0.1:4000/api/health/ready').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" >/dev/null 2>&1; then
    log "backend ready"
    break
  fi
  sleep 5
done

$COMPOSE ps
log "done"
log "MQTT  mqtts://$MQTT_HOST_NAME:8883"
log "API   https://$API_HOST_NAME"
